### ISSUE TITLE
전공동아리나 자율동아리를 두개이상 만들려고 하면  나는 에러메세지가 이상합니다!

### ISSUE THREAD

**Issue by kimsh153** [GSM-MSG/GCMS-iOS#130]
전공동아리나 자율동아리를 두개이상 만들려고 하면  나는 에러메세지가 이상합니다!
인터넷이 연결되지 않습니다라는 오류가 뜹니다 이 오류 대신에 전공동아리 또는 자율동아리가 이미 있습니다 같은 에러메시지로 변경 부탁드립니다

**Comment by baekteun** [comment]
아 업뎃함ㅅㄱ
